const GROUP = {
    GET_GROUPS_PENDING: "GET_GROUPS_PENDING",
    GET_GROUPS_SUCCESS: "GET_GROUPS_SUCCESS",
    GET_GROUPS_FAIL: "GET_GROUPS_FAIL",
    
    ADD_GROUP: "ADD_GROUP",
    PREV_GROUP: "PREV_GROUP",
    NEXT_GROUP: "NEXT_GROUP",
    REMOVE_GROUPS: "REMOVE_GROUPS",
}

const DATA = {
    GET_DATA_PENDING: "GET_DATA_PENDING",
    GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
    GET_DATA_FAIL: "GET_DATA_FAIL",
    REMOVE_DATA: "REMOVE_DATA",
    SET_LAST_UPDATE: "SET_LAST_UPDATE",
    REMOVE_LAST_UPDATE: "REMOVE_LAST_UPDATE",
}

export default {
    ...GROUP,
    ...DATA,
}